app:
  name: PyLine
  version: 0.5.0
  env: production
  debug: false
  maintenance_mode: false
paths:
  commands:
  - ./src/pccl/commands
  - plugins
  logs: ./logs
  session: ./session
  theme:
  - ./theme
logging:
  level: INFO
  rotation:
    max_size: 10MB
    backup_count: 7
    compress: true
  format: '%(asctime)s | %(levelname)-8s | %(module)s: %(message)s'
locale:
  language: en_US
  timezone: UTC
  datetime_format: iso
  units_system: metric
modules:
  core:
  - commands.essentials.env
  - commands.essentials.meta
  - commands.essentials.output
  - commands.essentials.sctrl
  - commands.theme.theme
  plugins:
  - ' '
user:
  theme:
    current: GitHub Light
    available:
    - GitHub Dark
    - GitHub Dark High Contrast
    - GitHub Light
    - Simple Light
  styles: null
  shortcuts:
    command_search: Ctrl+K
    history: Ctrl+H
  history_size: 1000
  auto_update: true
